version: "3.9"

services:
  redis:
    restart: unless-stopped
    image: redis:alpine
    expose:
      - 6379
  celery:
    restart: always
    build:
      context: .
    command: celery -A uptimechecker worker -B -l INFO
    volumes:
      - static_volume:/code
    depends_on:
      - redis
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: uptimechecker-django
    volumes:
      - static_volume:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
volumes:
    static_volume: {}
