version: "3.9"

services:
  redis:
    restart: unless-stopped
    image: redis:alpine
    expose:
      - 6379
  celery:
    restart: always
    build:
      context: .
    command: celery -A uptimechecker worker -B -l INFO
    environment:
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - .:/code
    depends_on:
      - redis
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: uptimechecker-django
    volumes:
      - .:/code
    environment:
      IS_DOCKER: "true"
      REDIS_URL: "redis://redis:6379/0"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
#volumes:
#    django: {}
