# Generated by Django 4.1.1 on 2022-09-19 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetWebsite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=400)),
                ('must_contain_keyword', models.CharField(default='', max_length=400)),
                ('flag_cdn_random_key', models.BooleanField(default=True)),
                ('flag_check_ssl_expire_time', models.BooleanField(default=True, verbose_name='Check SSL Expire Time')),
                ('ssl_expire_time', models.DateTimeField(blank=True, null=True)),
                ('flag_notify_downtime', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='UptimeCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=400)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('checking', '0: Checking'), ('normal', '1: Normal'), ('error', '2: Error'), ('exception', '3: Exception'), ('missing_keyword', '4: Missing Keyword')], max_length=200, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload')),
                ('target_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uptimebot.targetwebsite')),
            ],
        ),
    ]
