# Generated by Django 4.1.1 on 2022-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptimebot', '0003_alter_targetwebsite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uptimecheck',
            name='http_type',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('HEAD', 'HEAD')], default='GET', max_length=20),
        ),
        migrations.AlterField(
            model_name='targetwebsite',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the website (Optional)', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='uptimecheck',
            name='status',
            field=models.CharField(blank=True, choices=[('checking', 'Checking'), ('normal', 'Normal'), ('error', 'Error'), ('exception', 'Exception'), ('missing_keyword', 'Missing Keyword')], max_length=200, null=True),
        ),
    ]
