# Generated by Django 4.2.1 on 2023-05-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptimebot', '0004_uptimecheck_http_type_alter_targetwebsite_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetwebsite',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
