# Generated by Django 4.2.1 on 2023-05-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptimebot', '0005_targetwebsite_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetwebsite',
            name='flag_notify_slack_downtime',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='targetwebsite',
            name='notifications_suppressed_until_date',
            field=models.DateTimeField(blank=True, help_text='Suppress all notifications', null=True),
        ),
    ]
