# Generated by Django 4.2.1 on 2023-05-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uptimebot', '0006_targetwebsite_flag_notify_slack_downtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetwebsite',
            old_name='flag_notify_downtime',
            new_name='flag_notify_email_downtime',
        ),
    ]
